### ISSUE TITLE
error adding the ios platform

### ISSUE THREAD

**Issue by scottbrodersen** [Adobe-Marketing-Cloud-Apps/aem-phonegap-starter-kit#10]
When I add the iOS platform to the project, I get an error (about 10 times, same error) that it cannot find the icon file:

<code>sbroders-2015:ShapesCon-dev.1446731874255 sbroders$ cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.9.2
cp: no such file or directory: /Users/sbroders/Documents/6.1/Apps/ShapesCon-dev.1446731874255/icon.png</code>

Seems like it should be looking in the www folder instead of the project folder.

**Comment by blefebvre** [comment]
`icon.png` is now in the expected location, so this error should no longer occur.
